### PR TITLE
minor fix for a coredump

### PR DESCRIPTION
**Pull request by brendangregg**

### CODE REVIEW

**Comment by indutny** [comment]
Thank you! LGTM

**Comment by indutny** [comment]
Landed in 7ce1b78 and 7105017.

**Comment by indutny** [comment]
homebrew PR: https://github.com/Homebrew/homebrew-core/pull/2847

**Comment by indutny** [comment]
brew PR landed.

**Comment by indutny** [comment]
Thank you again, @brendangregg !

**Comment by brendangregg** [comment]
What was the Homebrew stuff? If I sent more PRs, is it anything I need to be aware of? :)

**Pull request closed without merging**
