### PR TITLE
llnode: add support for JSDate

### PR DESCRIPTION
**Pull request by evanlucas**
Result:

```
(lldb) v8 i 0x000001a3f3124551
0x000001a3f3124551:<JSDate: 1447105503556>

$ node
> new Date(1447105503556)
Mon Nov 09 2015 15:45:03 GMT-0600 (CST)
```

### CODE REVIEW

**Comment by indutny** [comment]
@evanlucas looks like you updated it. Is it ready for review?

**Comment by evanlucas** [comment]
Yep. Thanks a bunch for the guidance. :]

**Comment by indutny** [comment]
LGTM, let me test it.

**Comment by evanlucas** [comment]
Speaking of tests, have you thought about a way to automate tests?

**Comment by indutny** [comment]
This sounds like a good idea. Any ideas on how to do it?

Btw, landed in 46c8924. Thanks!

**Pull request closed without merging**
